Re-tabbed and adjusted modeline

diff --git a/mac-cleanup b/mac-cleanup
--- a/mac-cleanup
+++ b/mac-cleanup
@@ -1,18 +1,23 @@
 #!/usr/bin/env bash
-# vim: ai:ts=2:sw=2:et
+# vim: sw=2 sts=2 et
+#
+# mac-cleanup
+#
+# A Mac Cleaning up Utility by fwartner
+# https://github.com/mac-cleanup/mac-cleanup-sh
 
 set -E
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 cleanup() {
-	trap - SIGINT SIGTERM ERR EXIT
+  trap - SIGINT SIGTERM ERR EXIT
 }
 
 # Default arguments
 update=false
 
 usage() {
-	cat <<EOF
+  cat <<EOF
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-u]
 
 A Mac Cleaning up Utility by fwartner
@@ -25,80 +30,80 @@ Available options:
 -v, --verbose    Print script debug info
 -u, --update     Run brew update
 EOF
-	exit
+exit
 }
 
 # shellcheck disable=SC2034  # Unused variables left for readability
 setup_colors() {
-	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
-	else
-		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
-	fi
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
 }
 
 msg() {
   if [[ -z "$dry_run" ]]; then
-	  echo >&2 -e "${1-}"
-	fi
+    echo >&2 -e "${1-}"
+  fi
 }
 
 die() {
-	local msg=$1
-	local code=${2-1} # default exit status 1
-	msg "$msg"
-	exit "$code"
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
 }
 
 parse_params() {
-	# default values of variables set from params
-	update=false
+  # default values of variables set from params
+  update=false
 
-	while :; do
-		case "${1-}" in
-		-h | --help) usage ;;
-		-v | --verbose) set -x ;;
-		-d | --dry-run) dry_run=true ;;
-		--no-color) NO_COLOR=1 ;;
-		-u | --update) update=true ;; # update flag
-		-n) true ;;                   # This is a legacy option, now default behaviour
-		-?*) die "Unknown option: $1" ;;
-		*) break ;;
-		esac
-		shift
-	done
+  while :; do
+    case "${1-}" in
+      -h | --help) usage ;;
+      -v | --verbose) set -x ;;
+      -d | --dry-run) dry_run=true ;;
+      --no-color) NO_COLOR=1 ;;
+      -u | --update) update=true ;; # update flag
+      -n) true ;;                   # This is a legacy option, now default behaviour
+      -?*) die "Unknown option: $1" ;;
+      *) break ;;
+    esac
+    shift
+  done
 
-	return 0
+  return 0
 }
 
 parse_params "$@"
 setup_colors
 
 deleteCaches() {
-	local cacheName=$1
-	shift
-	local paths=("$@")
-	echo "Initiating cleanup ${cacheName} cache..."
-	for folderPath in "${paths[@]}"; do
-		if [[ -d ${folderPath} ]]; then
-			dirSize=$(du -hs "${folderPath}" | awk '{print $1}')
-			echo "Deleting ${folderPath} to free up ${dirSize}..."
-			rm -rfv "${folderPath}"
-		fi
-	done
+  local cacheName=$1
+  shift
+  local paths=("$@")
+  echo "Initiating cleanup ${cacheName} cache..."
+  for folderPath in "${paths[@]}"; do
+    if [[ -d ${folderPath} ]]; then
+      dirSize=$(du -hs "${folderPath}" | awk '{print $1}')
+      echo "Deleting ${folderPath} to free up ${dirSize}..."
+      rm -rfv "${folderPath}"
+    fi
+  done
 }
 
 bytesToHuman() {
-	b=${1:-0}
-	d=''
-	s=1
-	S=(Bytes {K,M,G,T,E,P,Y,Z}iB)
-	while ((b > 1024)); do
-		d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
-		b=$((b / 1024))
-		((s++))
-	done
-	if [[ -z "$dry_results" ]]; then
+  b=${1:-0}
+  d=''
+  s=1
+  S=(Bytes {K,M,G,T,E,P,Y,Z}iB)
+  while ((b > 1024)); do
+    d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
+    b=$((b / 1024))
+    ((s++))
+  done
+  if [[ -z "$dry_results" ]]; then
     msg "$b$d ${S[$s]} of space was cleaned up"
   else
     msg "Approx $b$d ${S[$s]} of space will be cleaned up"
@@ -106,7 +111,7 @@ bytesToHuman() {
 }
 
 count_dry() {
-	(( ${#path_list[@]} == 0 )) && return
+  (( ${#path_list[@]} == 0 )) && return
   for path in "${path_list[@]}"; do
     if [[ -d "$path" ]] || [[ -f "$path" ]]; then
       temp_dry_results=$(sudo du -ck "$path" | tail -1 | awk '{ print $1 }')
@@ -116,7 +121,7 @@ count_dry() {
 }
 
 remove_paths() {
-	(( ${#path_list[@]} == 0 )) && return
+  (( ${#path_list[@]} == 0 )) && return
   if [[ -z "$dry_run" ]]; then
     for path in "${path_list[@]}"; do
       rm -rfv "$path" &>/dev/null
@@ -126,10 +131,10 @@ remove_paths() {
 }
 
 collect_paths() {
-	(( ${#@[@]} == 0 )) && return
-	for path in $@; do
-		[[ -d "$path" ]] || [[ -f "$path" ]] && path_list+=("$path")
-	done
+  (( ${#@[@]} == 0 )) && return
+  for path in $@; do
+    [[ -d "$path" ]] || [[ -f "$path" ]] && path_list+=("$path")
+  done
 }
 
 # Ask for the administrator password upfront
@@ -137,9 +142,9 @@ sudo -v
 
 # Keep-alive sudo until `mac-cleanup.sh` has finished
 while true; do
-	sudo -n true
-	sleep 60
-	kill -0 "$$" || exit
+  sudo -n true
+  sleep 60
+  kill -0 "$$" || exit
 done 2>/dev/null &
 
 # Enable extended regex
@@ -269,13 +274,13 @@ fi
 # Deletes Minecraft logs
 # -Astro
 if [[ -d "$HOME/Library/Application Support/minecraft" ]]; then
-	collect_paths "$HOME/Library/Application Support/minecraft/logs"
-	collect_paths "$HOME/Library/Application Support/minecraft/crash-reports"
-	collect_paths "$HOME/Library/Application Support/minecraft/webcache"
-	collect_paths "$HOME/Library/Application Support/minecraft/webcache2"
-	collect_paths "$HOME/Library/Application Support/minecraft/crash-reports"
-	collect_paths "$HOME/Library/Application Support/minecraft/"*.log
-	collect_paths "$HOME/Library/Application Support/minecraft/launcher_cef_log.txt"
+  collect_paths "$HOME/Library/Application Support/minecraft/logs"
+  collect_paths "$HOME/Library/Application Support/minecraft/crash-reports"
+  collect_paths "$HOME/Library/Application Support/minecraft/webcache"
+  collect_paths "$HOME/Library/Application Support/minecraft/webcache2"
+  collect_paths "$HOME/Library/Application Support/minecraft/crash-reports"
+  collect_paths "$HOME/Library/Application Support/minecraft/"*.log
+  collect_paths "$HOME/Library/Application Support/minecraft/launcher_cef_log.txt"
 
   if [[ -d "$HOME/Library/Application Support/minecraft/.mixin.out" ]]; then
     collect_paths "$HOME/Library/Application Support/minecraft/.mixin.out"
@@ -483,7 +488,7 @@ shopt -u extglob
 if [[ -z "$dry_run" ]]; then
   msg "${GREEN}Success!${NOFORMAT}"
 
-	# Calculate the change in available disk space
+  # Calculate the change in available disk space
   newAvailable=$(df / | tail -1 | awk '{print $4}')
   count=$((newAvailable - oldAvailable))
   bytesToHuman $count
